#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-mako
Version  : 1.2.0
Release  : 93
URL      : https://files.pythonhosted.org/packages/50/ec/1d687348f0954bda388bfd1330c158ba8d7dea4044fc160e74e080babdb9/Mako-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/50/ec/1d687348f0954bda388bfd1330c158ba8d7dea4044fc160e74e080babdb9/Mako-1.2.0.tar.gz
Summary  : A super-fast templating language that borrows the best ideas from the existing templating languages.
Group    : Development/Tools
License  : MIT
Requires: pypi-mako-bin = %{version}-%{release}
Requires: pypi-mako-license = %{version}-%{release}
Requires: pypi-mako-python = %{version}-%{release}
Requires: pypi-mako-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(markupsafe)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
=========================
Mako Templates for Python
=========================
Mako is a template library written in Python. It provides a familiar, non-XML
syntax which compiles into Python modules for maximum performance. Mako's
syntax and API borrows from the best ideas of many others, including Django
templates, Cheetah, Myghty, and Genshi. Conceptually, Mako is an embedded
Python (i.e. Python Server Page) language, which refines the familiar ideas
of componentized layout and inheritance to produce one of the most
straightforward and flexible models available, while also maintaining close
ties to Python calling and scoping semantics.

%package bin
Summary: bin components for the pypi-mako package.
Group: Binaries
Requires: pypi-mako-license = %{version}-%{release}

%description bin
bin components for the pypi-mako package.


%package license
Summary: license components for the pypi-mako package.
Group: Default

%description license
license components for the pypi-mako package.


%package python
Summary: python components for the pypi-mako package.
Group: Default
Requires: pypi-mako-python3 = %{version}-%{release}

%description python
python components for the pypi-mako package.


%package python3
Summary: python3 components for the pypi-mako package.
Group: Default
Requires: python3-core
Provides: pypi(mako)
Requires: pypi(markupsafe)

%description python3
python3 components for the pypi-mako package.


%prep
%setup -q -n Mako-1.2.0
cd %{_builddir}/Mako-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649783950
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mako
cp %{_builddir}/Mako-1.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mako/eafe808420347be680db267888cb2f6be967c615
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mako-render

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mako/eafe808420347be680db267888cb2f6be967c615

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
